version: "3.8"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - FWMT_PUBSUB_HOST=localhost
      - FWMT_PUBSUB_EMULATOR_PORT=8085
      - FWMT_PUBSUB_PROJECT=fwmt-local
      - FWMT_PUBSUB_TOPIC=RM.Field
      - CASES_TO_FETCH=10
      - TMMOCK_API_URL=http://fwmtgatewaytmmock:8000/cases/
